//
//  ContentTaggingService.swift
//  OpenIntelligence
//
//  Created by GitHub Copilot on 1/9/26.
//
//  Leverages Apple's FoundationModels contentTagging use case to auto-label documents
//  with topics, actions, emotions, and objects. This specialized model is optimized
//  for categorization tasks and runs entirely on-device.
//
//  Reference: https://developer.apple.com/documentation/foundationmodels/categorizing-and-organizing-data-with-content-tags

import Foundation
import NaturalLanguage

#if canImport(FoundationModels)
    import FoundationModels

    private enum ContentTaggingError: LocalizedError {
        case timedOut(seconds: UInt64)

        var errorDescription: String? {
            switch self {
            case let .timedOut(seconds):
                return "Content tagging timed out after \(seconds)s."
            }
        }
    }

    /// Content tags generated by Apple's content tagging model
    /// Uses @Generable for structured output with controlled tag counts
    @available(iOS 26.0, *)
    @Generable
    struct ContentTags: Sendable, Codable {
        @Guide(
            description: "The 1-3 most important topics in the document (e.g., 'machine learning', 'finance', 'cooking').",
            .maximumCount(3)
        )
        let topics: [String]

        @Guide(
            description: "Key actions or processes described in the document (e.g., 'analyzing', 'building', 'teaching').",
            .maximumCount(2)
        )
        let actions: [String]

        @Guide(
            description: "Primary emotions or tones conveyed (e.g., 'informative', 'urgent', 'optimistic').",
            .maximumCount(2)
        )
        let emotions: [String]

        @Guide(
            description: "Important objects, entities, or concepts mentioned (e.g., 'neural networks', 'budget', 'ingredients').",
            .maximumCount(3)
        )
        let objects: [String]

        /// All tags flattened into a single array for display/storage
        var allTags: [String] {
            var result: [String] = []
            result.append(contentsOf: topics)
            result.append(contentsOf: actions)
            result.append(contentsOf: emotions)
            result.append(contentsOf: objects)
            return result
        }

        /// Tags formatted for display (deduplicated, lowercase, sorted)
        var displayTags: [String] {
            let unique = Set(allTags.map { $0.lowercased().trimmingCharacters(in: .whitespaces) })
            return unique.sorted()
        }

        /// Empty tags instance for fallback
        static let empty = ContentTags(topics: [], actions: [], emotions: [], objects: [])
    }

    /// Service for generating content tags using Apple's specialized content tagging model
    /// This model is separate from the general-purpose LLM and is optimized for categorization
    @available(iOS 26.0, *)
    @MainActor
    final class ContentTaggingService {
        // MARK: - Configuration

        nonisolated private static let generationTimeoutSeconds: UInt64 = 8

        // MARK: - Singleton

        static let shared = ContentTaggingService()

        // MARK: - Properties

        /// The content tagging model (separate from general LLM)
        private var model: SystemLanguageModel?

        /// Active session for tagging
        private var session: LanguageModelSession?

        /// Whether the service is available
        var isAvailable: Bool {
            guard let model = model else { return false }
            switch model.availability {
            case .available:
                return true
            default:
                return false
            }
        }

        // MARK: - Initialization

        private init() {
            setupModel()
        }

        private func setupModel() {
            // Use the specialized content tagging model
            model = SystemLanguageModel(useCase: .contentTagging)

            if let model = model {
                switch model.availability {
                case .available:
                    Log.info("[ContentTagging] Content tagging model available", category: .llm)
                case let .unavailable(reason):
                    Log.warning("[ContentTagging] Model unavailable: \(reason)", category: .llm)
                @unknown default:
                    Log.warning("[ContentTagging] Model availability unknown", category: .llm)
                }
            }
        }

        // MARK: - Tag Generation

        /// Generate content tags for a document's text
        /// - Parameters:
        ///   - text: The document text to analyze (will be truncated if too long)
        ///   - documentName: Optional document name for logging
        /// - Returns: ContentTags with topics, actions, emotions, and objects
        func generateTags(for text: String, documentName: String? = nil) async throws -> ContentTags {
            guard model != nil else {
                Log.warning("[ContentTagging] Model not initialized", category: .llm)
                return .empty
            }

            guard isAvailable else {
                Log.warning("[ContentTagging] Model not available", category: .llm)
                return .empty
            }

            let startTime = Date()

            // Truncate text to fit in context window (content tagging model has same 4096 limit)
            // Reserve ~500 tokens for response, use ~3000 for content (~7500 chars conservative)
            let maxChars = 7500
            let truncatedText: String
            if text.count > maxChars {
                truncatedText = String(text.prefix(maxChars)) + "..."
                Log.debug("[ContentTagging] Text truncated from \(text.count) to \(maxChars) chars", category: .llm)
            } else {
                truncatedText = text
            }

            // Create fresh session for each tagging request (content tagging sessions are lightweight)
            let instructions = """
            Analyze the provided text and identify the most significant:
            - Topics: Main subjects or themes (1-3 tags)
            - Actions: Key activities or processes described (1-2 tags)
            - Emotions: Overall tone or sentiment (1-2 tags)
            - Objects: Important entities, concepts, or things mentioned (1-3 tags)

            Use lowercase, concise tags (1-3 words each).
            """

            // `model:` is required. Omitting it yields a session that produces no output: an Instruments
            // capture on 2026-08-15 recorded two such calls returning 0 tokens over 6.5 and 7.1
            // seconds with an empty Response, while every session built with an explicit model
            // succeeded in the same run. The bare `LanguageModelSession()` initialiser was fixed at
            // ten sites on 2026-08-14; these pass instructions but still omitted the model, so they
            // were missed by a grep for the no-argument form.
            session = LanguageModelSession(model: SystemLanguageModel.default, instructions: instructions)

            guard let session = session else {
                Log.error("[ContentTagging] Failed to create session", category: .llm)
                return .empty
            }

            HardwareTelemetryState.shared.sustain(.llmInference, active: true, intensity: 0.7)
            defer {
                HardwareTelemetryState.shared.sustain(.llmInference, active: false)
            }
            Log.info("[ContentTagging] Generating tags for \(documentName ?? "document") with \(Self.generationTimeoutSeconds)s timeout", category: .llm)

            do {
                let tags = try await generateTagsWithTimeout(
                    session: session,
                    text: truncatedText
                )
                let elapsed = Date().timeIntervalSince(startTime)
                DSHaptics.soft()

                Log.info(
                    "[ContentTagging] Generated \(tags.displayTags.count) tags in \(String(format: "%.2f", elapsed))s for \(documentName ?? "document"): \(tags.displayTags.joined(separator: ", "))",
                    category: .llm
                )

                return tags

            } catch let error as LanguageModelSession.GenerationError {
                switch error {
                case .exceededContextWindowSize:
                    Log.warning("[ContentTagging] Context overflow, retrying with shorter text", category: .llm)
                    let shortText = String(text.prefix(2000))
                    return try await generateTags(for: shortText, documentName: documentName)

                case .guardrailViolation, .refusal:
                    // Apple FM flagged the document content as sensitive — use NLTagger fallback
                    Log.info("[ContentTagging] Content flagged by Apple FM safety filter, using NLTagger fallback for \(documentName ?? "document")", category: .llm)
                    return nlTaggerFallbackTags(for: text)

                default:
                    Log.warning("[ContentTagging] Generation error: \(error)", category: .llm)
                    return nlTaggerFallbackTags(for: text)
                }
            } catch let error as ContentTaggingError {
                Log.warning("[ContentTagging] \(error.localizedDescription) Using NLTagger fallback for \(documentName ?? "document")", category: .llm)
                return nlTaggerFallbackTags(for: text)
            } catch {
                // On iOS 27 a context overflow arrives as `LanguageModelError.contextSizeExceeded`,
                // which does not match the typed catch above, so the shorten-and-retry recovery was
                // unreachable and every overflow silently degraded to keyword tagging.
                //
                // The length check is not in the original branch and is needed: it retried with
                // `text.prefix(2000)` unconditionally, so a text already at or under 2000 characters
                // would recurse on an identical string forever.
                if FoundationModelErrorMapper.recoveryHint(for: error) == .contextOverflow,
                   text.count > 2000 {
                    Log.warning("[ContentTagging] Context overflow, retrying with shorter text", category: .llm)
                    return try await generateTags(for: String(text.prefix(2000)), documentName: documentName)
                }
                Log.warning("[ContentTagging] Unexpected error: \(error), using NLTagger fallback", category: .llm)
                return nlTaggerFallbackTags(for: text)
            }
        }

        private func generateTagsWithTimeout(
            session: LanguageModelSession,
            text: String
        ) async throws -> ContentTags {
            try Task.checkCancellation()

            return try await withThrowingTaskGroup(of: ContentTags.self) { group in
                group.addTask {
                    let response = try await session.respond(
                        to: text,
                        generating: ContentTags.self
                    )
                    return response.content
                }

                group.addTask {
                    try await Task.sleep(nanoseconds: Self.generationTimeoutSeconds * 1_000_000_000)
                    throw ContentTaggingError.timedOut(seconds: Self.generationTimeoutSeconds)
                }

                guard let result = try await group.next() else {
                    throw ContentTaggingError.timedOut(seconds: Self.generationTimeoutSeconds)
                }
                group.cancelAll()
                return result
            }
        }

        /// Generate tags for a document by sampling multiple chunks
        /// This provides better coverage than just using the beginning
        func generateTagsForDocument(chunks: [String], documentName: String? = nil) async throws -> ContentTags {
            guard !chunks.isEmpty else { return .empty }

            // Sample strategy: beginning, middle, and end for better coverage
            var sampleText = ""
            let maxSampleChars = 6000

            if chunks.count == 1 {
                sampleText = chunks[0]
            } else if chunks.count == 2 {
                sampleText = chunks[0] + "\n\n" + chunks[1]
            } else {
                // Take first chunk, a middle chunk, and last chunk
                let middleIndex = chunks.count / 2
                sampleText = chunks[0] + "\n\n" + chunks[middleIndex] + "\n\n" + chunks[chunks.count - 1]
            }

            // Truncate if still too long
            if sampleText.count > maxSampleChars {
                sampleText = String(sampleText.prefix(maxSampleChars))
            }

            return try await generateTags(for: sampleText, documentName: documentName)
        }

        // MARK: - NLTagger Fallback

        /// When Apple FM refuses the document content (sensitive/medical/legal text),
        /// extract tags using NLTagger instead — no LLM needed, never refuses.
        private func nlTaggerFallbackTags(for text: String) -> ContentTags {
            let sample = String(text.prefix(5000))
            guard !sample.isEmpty else { return .empty }

            let tagger = NLTagger(tagSchemes: [.nameType, .lexicalClass])
            tagger.string = sample
            let opts: NLTagger.Options = [.omitWhitespace, .omitPunctuation, .joinNames]

            var topics: [String] = []
            var actions: [String] = []
            var objects: [String] = []

            // Generic filler words to skip
            let skip: Set<String> = [
                "information", "data", "system", "process", "method", "type", "result",
                "value", "level", "step", "point", "case", "thing", "fact", "issue",
                "content", "detail", "feature", "section", "part", "example", "item",
                "number", "time", "way", "use", "need", "order", "form", "rate",
                "state", "area", "line", "note", "text", "page", "word", "mode",
            ]

            // Named entities → topics
            tagger.enumerateTags(in: sample.startIndex..<sample.endIndex, unit: .word, scheme: .nameType, options: opts) { tag, range in
                if let tag, [.personalName, .placeName, .organizationName].contains(tag) {
                    let entity = String(sample[range]).trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
                    if entity.count >= 2, entity.count <= 30, !topics.contains(entity) {
                        topics.append(entity)
                    }
                }
                return topics.count < 3
            }

            // Nouns → objects, Verbs → actions
            tagger.enumerateTags(in: sample.startIndex..<sample.endIndex, unit: .word, scheme: .lexicalClass, options: opts) { tag, range in
                let word = String(sample[range]).trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
                guard word.count >= 3, word.count <= 20, !skip.contains(word) else { return true }

                if tag == .noun, !objects.contains(word) {
                    objects.append(word)
                } else if tag == .verb, !actions.contains(word) {
                    actions.append(word)
                }
                return objects.count < 3 && actions.count < 2
            }

            // If no named entities found, promote top nouns to topics
            if topics.isEmpty, objects.count >= 2 {
                topics = Array(objects.prefix(2))
                objects = Array(objects.dropFirst(2))
            }

            let tags = ContentTags(
                topics: Array(topics.prefix(3)),
                actions: Array(actions.prefix(2)),
                emotions: ["informative"],  // safe default
                objects: Array(objects.prefix(3))
            )

            Log.info("[ContentTagging] NLTagger fallback: \(tags.displayTags.joined(separator: ", "))", category: .llm)
            return tags
        }
    }

#else

    // MARK: - Fallback for non-iOS 26

    /// Placeholder for platforms without FoundationModels
    struct ContentTags: Sendable, Codable {
        let topics: [String]
        let actions: [String]
        let emotions: [String]
        let objects: [String]

        var allTags: [String] { topics + actions + emotions + objects }
        var displayTags: [String] { Set(allTags.map { $0.lowercased() }).sorted() }
        static let empty = ContentTags(topics: [], actions: [], emotions: [], objects: [])
    }

    /// Placeholder service that returns empty tags
    @MainActor
    final class ContentTaggingService {
        static let shared = ContentTaggingService()
        var isAvailable: Bool { false }

        func generateTags(for _: String, documentName _: String? = nil) async throws -> ContentTags {
            return .empty
        }

        func generateTagsForDocument(chunks _: [String], documentName _: String? = nil) async throws -> ContentTags {
            return .empty
        }
    }

#endif
