#!/usr/bin/env bash

# Public demo export boundary for syncing the private engine repo into the
# existing OpenIntelligence-Public working copy.
#
# Source of truth principle:
# - private engine repo is authoritative
# - public repo is a curated export target
# - allowlist paths are mirrored intentionally
# - denylist paths are explicitly removed from the public repo

PUBLIC_EXPORT_PATHS=(
  ".github/ISSUE_TEMPLATE"
  ".github/PULL_REQUEST_TEMPLATE.md"
  ".github/workflows/ci.yml"
  ".github/workflows/release.yml"
  ".gitignore"
  ".gitmodules"
  ".swift-format"
  "ARCHITECTURE.md"
  "CHANGELOG.md"
  "Docs/TestDocuments"
  "Docs/reference"
  "Gemfile"
  "Gemfile.lock"
  "HOW_IT_WORKS.md"
  "Info.plist"
  "LICENSE"
  "PRIVACY.md"
  "README.md"
  "ROADMAP.md"
  "THIRD_PARTY_NOTICES.md"
  "WHATS_NEW.md"
  "OpenIntelligence/Resources/Assets"
  "OpenIntelligence/Resources/PrivacyInfo.xcprivacy"
  "OpenIntelligence/Resources/StoreKit"
  "OpenIntelligence.xcodeproj"
  "clean_and_rebuild.sh"
  "fastlane"
  "marketing"
  "scripts/analyze_pdf.py"
  "scripts/build_simulator_smoke.sh"
  "scripts/check_app_store_connect_products.swift"
  "scripts/create_version.rb"
  "scripts/package_submission.sh"
  "scripts/preflight_check.sh"
  "scripts/pull_trace.sh"
  "scripts/push_draft_metadata.rb"
  "scripts/push_metadata.rb"
  "scripts/push_promo_draft.rb"
  "scripts/secret_scan.py"
  "scripts/take_screenshots.sh"
  "scripts/validate_env.sh"
  "scripts/verify_asc_products.rb"
  "scripts/verify_storekit_products.swift"
)

PUBLIC_DELETE_PATHS=(
  ".github/copilot-instructions.md"
  ".github/instructions"
  "BenchmarkRuns"
  "Benchmarks"
  "ENGINE_CAPABILITIES.md"
  "EngineSale"
  "FULLSPORTAGEMANUAL"
  "INTERNAL_LOGIC_AUDIT.md"
  "IngestionProcessofaRandomResearchPaper.txt"
  "OpenIntelligence/Core"
  "OpenIntelligence/Features"
  "OpenIntelligence/Core/Support"
  "OpenIntelligence/Resources/MLModels"
  "OpenIntelligence/SDK"
  "OpenIntelligence/Services"
  "OpenIntelligence/UI"
  "Package.resolved"
  "Package.swift"
  "Paper.txt"
  "PaperQuery.txt"
  "REGRESSION_PLAN.md"
  "SDK_BOUNDARY_AUDIT.md"
  "Samples"
  "SideProjectors.txt"
  "SportageFuelTankTrace"
  "SportageFuelTankTrace2"
  "SportageTraceFuelTankCapacity"
  "VISIBILITY_POLICY.md"
  "WORKFLOW.md"
  "output"
  "scripts/build_engine_evaluation_host.sh"
  "scripts/build_engine_evaluation_xcframework.sh"
  "scripts/build_engine_xcframework.sh"
  "scripts/build_partner_packet_bundle.sh"
  "scripts/build_sdk_buyer_bundle.sh"
  "scripts/clean_duplicate_output_artifacts.sh"
  "scripts/convert_embedding_model.py"
  "scripts/prepare_engine_buyer_packet.sh"
  "scripts/prepare_rag_research_fixtures.py"
  "scripts/prepare_sale_packets.sh"
  "scripts/promote_public_safe.sh"
  "scripts/rag_benchmark_studio.py"
  "scripts/refresh_public_signal.sh"
  "scripts/run_generation_audit.sh"
  "scripts/run_rag_benchmarks.py"
  "scripts/stage_sdk_sample_app.sh"
  "scripts/update_public_release_summary.sh"
  "scripts/validate_sdk_package.sh"
  "scripts/validate_source_sdk_consumer_flow.sh"
  "scripts/validate_source_sdk_package.sh"
)

PUBLIC_DEMO_OVERLAY_ROOT="public_demo_overlay"

PUBLIC_DEMO_REQUIRED_PATHS=(
  ".env.example"
  "OpenIntelligence/App/ContentView.swift"
  "OpenIntelligence/App/OpenIntelligenceApp.swift"
  "OpenIntelligence/PublicDemo/DemoViews.swift"
  "README.md"
  "ARCHITECTURE.md"
  "HOW_IT_WORKS.md"
  "fastlane/Fastfile"
  "fastlane/keys/.gitignore"
  "scripts/app_store_connect_env.rb"
  "scripts/create_version.rb"
  "scripts/push_draft_metadata.rb"
  "scripts/push_metadata.rb"
  "scripts/push_promo_draft.rb"
  "scripts/verify_asc_products.rb"
)
