//
//  ContentTaggingService.swift
//  OpenIntelligence
//
//  Created by GitHub Copilot on 1/9/26.
//
//  Leverages Apple's FoundationModels contentTagging use case to auto-label documents
//  with topics, actions, emotions, and objects. This specialized model is optimized
//  for categorization tasks and runs entirely on-device.
//
//  Reference: https://developer.apple.com/documentation/foundationmodels/categorizing-and-organizing-data-with-content-tags

import Foundation

#if canImport(FoundationModels)
    import FoundationModels

    /// Content tags generated by Apple's content tagging model
    /// Uses @Generable for structured output with controlled tag counts
    @available(iOS 26.0, *)
    @Generable
    struct ContentTags: Sendable, Codable {
        @Guide(
            description: "The 1-3 most important topics in the document (e.g., 'machine learning', 'finance', 'cooking').",
            .maximumCount(3)
        )
        let topics: [String]

        @Guide(
            description: "Key actions or processes described in the document (e.g., 'analyzing', 'building', 'teaching').",
            .maximumCount(2)
        )
        let actions: [String]

        @Guide(
            description: "Primary emotions or tones conveyed (e.g., 'informative', 'urgent', 'optimistic').",
            .maximumCount(2)
        )
        let emotions: [String]

        @Guide(
            description: "Important objects, entities, or concepts mentioned (e.g., 'neural networks', 'budget', 'ingredients').",
            .maximumCount(3)
        )
        let objects: [String]

        /// All tags flattened into a single array for display/storage
        var allTags: [String] {
            var result: [String] = []
            result.append(contentsOf: topics)
            result.append(contentsOf: actions)
            result.append(contentsOf: emotions)
            result.append(contentsOf: objects)
            return result
        }

        /// Tags formatted for display (deduplicated, lowercase, sorted)
        var displayTags: [String] {
            let unique = Set(allTags.map { $0.lowercased().trimmingCharacters(in: .whitespaces) })
            return unique.sorted()
        }

        /// Empty tags instance for fallback
        static let empty = ContentTags(topics: [], actions: [], emotions: [], objects: [])
    }

    /// Service for generating content tags using Apple's specialized content tagging model
    /// This model is separate from the general-purpose LLM and is optimized for categorization
    @available(iOS 26.0, *)
    @MainActor
    final class ContentTaggingService {
        // MARK: - Singleton

        static let shared = ContentTaggingService()

        // MARK: - Properties

        /// The content tagging model (separate from general LLM)
        private var model: SystemLanguageModel?

        /// Active session for tagging
        private var session: LanguageModelSession?

        /// Whether the service is available
        var isAvailable: Bool {
            guard let model = model else { return false }
            switch model.availability {
            case .available:
                return true
            default:
                return false
            }
        }

        // MARK: - Initialization

        private init() {
            setupModel()
        }

        private func setupModel() {
            // Use the specialized content tagging model
            model = SystemLanguageModel(useCase: .contentTagging)

            if let model = model {
                switch model.availability {
                case .available:
                    Log.info("[ContentTagging] Content tagging model available", category: .llm)
                case let .unavailable(reason):
                    Log.warning("[ContentTagging] Model unavailable: \(reason)", category: .llm)
                @unknown default:
                    Log.warning("[ContentTagging] Model availability unknown", category: .llm)
                }
            }
        }

        // MARK: - Tag Generation

        /// Generate content tags for a document's text
        /// - Parameters:
        ///   - text: The document text to analyze (will be truncated if too long)
        ///   - documentName: Optional document name for logging
        /// - Returns: ContentTags with topics, actions, emotions, and objects
        func generateTags(for text: String, documentName: String? = nil) async throws -> ContentTags {
            guard model != nil else {
                Log.warning("[ContentTagging] Model not initialized", category: .llm)
                return .empty
            }

            guard isAvailable else {
                Log.warning("[ContentTagging] Model not available", category: .llm)
                return .empty
            }

            let startTime = Date()

            // Truncate text to fit in context window (content tagging model has same 4096 limit)
            // Reserve ~500 tokens for response, use ~3000 for content (~7500 chars conservative)
            let maxChars = 7500
            let truncatedText: String
            if text.count > maxChars {
                truncatedText = String(text.prefix(maxChars)) + "..."
                Log.debug("[ContentTagging] Text truncated from \(text.count) to \(maxChars) chars", category: .llm)
            } else {
                truncatedText = text
            }

            // Create fresh session for each tagging request (content tagging sessions are lightweight)
            let instructions = """
            Analyze the provided text and identify the most significant:
            - Topics: Main subjects or themes (1-3 tags)
            - Actions: Key activities or processes described (1-2 tags)
            - Emotions: Overall tone or sentiment (1-2 tags)
            - Objects: Important entities, concepts, or things mentioned (1-3 tags)

            Use lowercase, concise tags (1-3 words each).
            """

            session = LanguageModelSession(instructions: instructions)

            guard let session = session else {
                Log.error("[ContentTagging] Failed to create session", category: .llm)
                return .empty
            }

            HardwareTelemetryState.shared.sustain(.llmInference, active: true, intensity: 0.7)

            do {
                let response = try await session.respond(
                    to: truncatedText,
                    generating: ContentTags.self
                )

                let tags = response.content
                let elapsed = Date().timeIntervalSince(startTime)
                HardwareTelemetryState.shared.sustain(.llmInference, active: false)
                DSHaptics.soft()

                Log.info(
                    "[ContentTagging] Generated \(tags.displayTags.count) tags in \(String(format: "%.2f", elapsed))s for \(documentName ?? "document"): \(tags.displayTags.joined(separator: ", "))",
                    category: .llm
                )

                return tags

            } catch let error as LanguageModelSession.GenerationError {
                switch error {
                case .exceededContextWindowSize:
                    HardwareTelemetryState.shared.sustain(.llmInference, active: false)
                    Log.warning("[ContentTagging] Context overflow, using shorter text sample", category: .llm)
                    // Retry with much shorter text
                    let shortText = String(text.prefix(2000))
                    return try await generateTags(for: shortText, documentName: documentName)

                case .guardrailViolation:
                    HardwareTelemetryState.shared.sustain(.llmInference, active: false)
                    Log.warning("[ContentTagging] Content flagged by guardrails", category: .llm)
                    return .empty

                default:
                    HardwareTelemetryState.shared.sustain(.llmInference, active: false)
                    Log.error("[ContentTagging] Generation error: \(error)", category: .llm)
                    return .empty
                }
            } catch {
                HardwareTelemetryState.shared.sustain(.llmInference, active: false)
                Log.error("[ContentTagging] Unexpected error: \(error)", category: .llm)
                return .empty
            }
        }

        /// Generate tags for a document by sampling multiple chunks
        /// This provides better coverage than just using the beginning
        func generateTagsForDocument(chunks: [String], documentName: String? = nil) async throws -> ContentTags {
            guard !chunks.isEmpty else { return .empty }

            // Sample strategy: beginning, middle, and end for better coverage
            var sampleText = ""
            let maxSampleChars = 6000

            if chunks.count == 1 {
                sampleText = chunks[0]
            } else if chunks.count == 2 {
                sampleText = chunks[0] + "\n\n" + chunks[1]
            } else {
                // Take first chunk, a middle chunk, and last chunk
                let middleIndex = chunks.count / 2
                sampleText = chunks[0] + "\n\n" + chunks[middleIndex] + "\n\n" + chunks[chunks.count - 1]
            }

            // Truncate if still too long
            if sampleText.count > maxSampleChars {
                sampleText = String(sampleText.prefix(maxSampleChars))
            }

            return try await generateTags(for: sampleText, documentName: documentName)
        }
    }

#else

    // MARK: - Fallback for non-iOS 26

    /// Placeholder for platforms without FoundationModels
    struct ContentTags: Sendable, Codable {
        let topics: [String]
        let actions: [String]
        let emotions: [String]
        let objects: [String]

        var allTags: [String] { topics + actions + emotions + objects }
        var displayTags: [String] { Set(allTags.map { $0.lowercased() }).sorted() }
        static let empty = ContentTags(topics: [], actions: [], emotions: [], objects: [])
    }

    /// Placeholder service that returns empty tags
    @MainActor
    final class ContentTaggingService {
        static let shared = ContentTaggingService()
        var isAvailable: Bool { false }

        func generateTags(for _: String, documentName _: String? = nil) async throws -> ContentTags {
            return .empty
        }

        func generateTagsForDocument(chunks _: [String], documentName _: String? = nil) async throws -> ContentTags {
            return .empty
        }
    }

#endif
